// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance.Database;

namespace Persistance.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220225010930_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.PlayThing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Compania")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcíon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("RetriccionEdad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("PlayThing");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Compania = "avión",
                            Descripcíon = "Juguete: patito de goma de la compania avión para mayores de 76 años",
                            Imagen = "",
                            Nombre = "patito de goma",
                            Precio = 935.18m,
                            RetriccionEdad = 76
                        },
                        new
                        {
                            Id = 2,
                            Compania = "muñeca",
                            Descripcíon = "Juguete: patito de goma de la compania muñeca para mayores de 78 años",
                            Imagen = "",
                            Nombre = "patito de goma",
                            Precio = 55.52m,
                            RetriccionEdad = 78
                        },
                        new
                        {
                            Id = 3,
                            Compania = "pelota",
                            Descripcíon = "Juguete: tren de la compania pelota para mayores de 11 años",
                            Imagen = "",
                            Nombre = "tren",
                            Precio = 706.39m,
                            RetriccionEdad = 11
                        },
                        new
                        {
                            Id = 4,
                            Compania = "patito de goma",
                            Descripcíon = "Juguete: bicicleta de la compania patito de goma para mayores de 98 años",
                            Imagen = "",
                            Nombre = "bicicleta",
                            Precio = 143.99m,
                            RetriccionEdad = 98
                        },
                        new
                        {
                            Id = 5,
                            Compania = "bicicleta",
                            Descripcíon = "Juguete: ¿Quién es Quién? de la compania bicicleta para mayores de 61 años",
                            Imagen = "",
                            Nombre = "¿Quién es Quién?",
                            Precio = 712.46m,
                            RetriccionEdad = 61
                        },
                        new
                        {
                            Id = 6,
                            Compania = "avión",
                            Descripcíon = "Juguete: muñeca de la compania avión para mayores de 5 años",
                            Imagen = "",
                            Nombre = "muñeca",
                            Precio = 277.11m,
                            RetriccionEdad = 5
                        },
                        new
                        {
                            Id = 7,
                            Compania = "muñeca",
                            Descripcíon = "Juguete: osito de peluche de la compania muñeca para mayores de 78 años",
                            Imagen = "",
                            Nombre = "osito de peluche",
                            Precio = 753.47m,
                            RetriccionEdad = 78
                        },
                        new
                        {
                            Id = 8,
                            Compania = "Pictionary",
                            Descripcíon = "Juguete: patito de goma de la compania Pictionary para mayores de 97 años",
                            Imagen = "",
                            Nombre = "patito de goma",
                            Precio = 807.53m,
                            RetriccionEdad = 97
                        },
                        new
                        {
                            Id = 9,
                            Compania = "UNO",
                            Descripcíon = "Juguete: bicicleta de la compania UNO para mayores de 38 años",
                            Imagen = "",
                            Nombre = "bicicleta",
                            Precio = 342.71m,
                            RetriccionEdad = 38
                        },
                        new
                        {
                            Id = 10,
                            Compania = "patito de goma",
                            Descripcíon = "Juguete: cometa de la compania patito de goma para mayores de 17 años",
                            Imagen = "",
                            Nombre = "cometa",
                            Precio = 561.66m,
                            RetriccionEdad = 17
                        },
                        new
                        {
                            Id = 11,
                            Compania = "UNO",
                            Descripcíon = "Juguete: ¿Quién es Quién? de la compania UNO para mayores de 51 años",
                            Imagen = "",
                            Nombre = "¿Quién es Quién?",
                            Precio = 497.06m,
                            RetriccionEdad = 51
                        },
                        new
                        {
                            Id = 12,
                            Compania = "¿Quién es Quién?",
                            Descripcíon = "Juguete: bicicleta de la compania ¿Quién es Quién? para mayores de 94 años",
                            Imagen = "",
                            Nombre = "bicicleta",
                            Precio = 527.11m,
                            RetriccionEdad = 94
                        },
                        new
                        {
                            Id = 13,
                            Compania = "Parchís",
                            Descripcíon = "Juguete: UNO de la compania Parchís para mayores de 24 años",
                            Imagen = "",
                            Nombre = "UNO",
                            Precio = 161.58m,
                            RetriccionEdad = 24
                        },
                        new
                        {
                            Id = 14,
                            Compania = "Parchís",
                            Descripcíon = "Juguete: bicicleta de la compania Parchís para mayores de 93 años",
                            Imagen = "",
                            Nombre = "bicicleta",
                            Precio = 417.99m,
                            RetriccionEdad = 93
                        },
                        new
                        {
                            Id = 15,
                            Compania = "patito de goma",
                            Descripcíon = "Juguete: muñeca de la compania patito de goma para mayores de 28 años",
                            Imagen = "",
                            Nombre = "muñeca",
                            Precio = 104.33m,
                            RetriccionEdad = 28
                        },
                        new
                        {
                            Id = 16,
                            Compania = "osito de peluche",
                            Descripcíon = "Juguete: Parchís de la compania osito de peluche para mayores de 85 años",
                            Imagen = "",
                            Nombre = "Parchís",
                            Precio = 775.49m,
                            RetriccionEdad = 85
                        },
                        new
                        {
                            Id = 17,
                            Compania = "¿Quién es Quién?",
                            Descripcíon = "Juguete: cometa de la compania ¿Quién es Quién? para mayores de 38 años",
                            Imagen = "",
                            Nombre = "cometa",
                            Precio = 352.73m,
                            RetriccionEdad = 38
                        },
                        new
                        {
                            Id = 18,
                            Compania = "¿Quién es Quién?",
                            Descripcíon = "Juguete: pelota de la compania ¿Quién es Quién? para mayores de 66 años",
                            Imagen = "",
                            Nombre = "pelota",
                            Precio = 127.82m,
                            RetriccionEdad = 66
                        },
                        new
                        {
                            Id = 19,
                            Compania = "Pictionary",
                            Descripcíon = "Juguete: Pictionary de la compania Pictionary para mayores de 46 años",
                            Imagen = "",
                            Nombre = "Pictionary",
                            Precio = 625.74m,
                            RetriccionEdad = 46
                        },
                        new
                        {
                            Id = 20,
                            Compania = "muñeca",
                            Descripcíon = "Juguete: ¿Quién es Quién? de la compania muñeca para mayores de 32 años",
                            Imagen = "",
                            Nombre = "¿Quién es Quién?",
                            Precio = 977.00m,
                            RetriccionEdad = 32
                        },
                        new
                        {
                            Id = 21,
                            Compania = "cometa",
                            Descripcíon = "Juguete: cometa de la compania cometa para mayores de 1 años",
                            Imagen = "",
                            Nombre = "cometa",
                            Precio = 479.72m,
                            RetriccionEdad = 1
                        },
                        new
                        {
                            Id = 22,
                            Compania = "¿Quién es Quién?",
                            Descripcíon = "Juguete: ¿Quién es Quién? de la compania ¿Quién es Quién? para mayores de 69 años",
                            Imagen = "",
                            Nombre = "¿Quién es Quién?",
                            Precio = 265.99m,
                            RetriccionEdad = 69
                        },
                        new
                        {
                            Id = 23,
                            Compania = "avión",
                            Descripcíon = "Juguete: osito de peluche de la compania avión para mayores de 23 años",
                            Imagen = "",
                            Nombre = "osito de peluche",
                            Precio = 930.48m,
                            RetriccionEdad = 23
                        },
                        new
                        {
                            Id = 24,
                            Compania = "UNO",
                            Descripcíon = "Juguete: ¿Quién es Quién? de la compania UNO para mayores de 29 años",
                            Imagen = "",
                            Nombre = "¿Quién es Quién?",
                            Precio = 578.71m,
                            RetriccionEdad = 29
                        },
                        new
                        {
                            Id = 25,
                            Compania = "tren",
                            Descripcíon = "Juguete: ¿Quién es Quién? de la compania tren para mayores de 9 años",
                            Imagen = "",
                            Nombre = "¿Quién es Quién?",
                            Precio = 109.08m,
                            RetriccionEdad = 9
                        },
                        new
                        {
                            Id = 26,
                            Compania = "bicicleta",
                            Descripcíon = "Juguete: bicicleta de la compania bicicleta para mayores de 83 años",
                            Imagen = "",
                            Nombre = "bicicleta",
                            Precio = 893.49m,
                            RetriccionEdad = 83
                        },
                        new
                        {
                            Id = 27,
                            Compania = "UNO",
                            Descripcíon = "Juguete: cometa de la compania UNO para mayores de 89 años",
                            Imagen = "",
                            Nombre = "cometa",
                            Precio = 303.41m,
                            RetriccionEdad = 89
                        },
                        new
                        {
                            Id = 28,
                            Compania = "Pictionary",
                            Descripcíon = "Juguete: pelota de la compania Pictionary para mayores de 4 años",
                            Imagen = "",
                            Nombre = "pelota",
                            Precio = 373.36m,
                            RetriccionEdad = 4
                        },
                        new
                        {
                            Id = 29,
                            Compania = "pelota",
                            Descripcíon = "Juguete: UNO de la compania pelota para mayores de 83 años",
                            Imagen = "",
                            Nombre = "UNO",
                            Precio = 815.33m,
                            RetriccionEdad = 83
                        },
                        new
                        {
                            Id = 30,
                            Compania = "bicicleta",
                            Descripcíon = "Juguete: tren de la compania bicicleta para mayores de 40 años",
                            Imagen = "",
                            Nombre = "tren",
                            Precio = 826.89m,
                            RetriccionEdad = 40
                        },
                        new
                        {
                            Id = 31,
                            Compania = "¿Quién es Quién?",
                            Descripcíon = "Juguete: avión de la compania ¿Quién es Quién? para mayores de 65 años",
                            Imagen = "",
                            Nombre = "avión",
                            Precio = 309.83m,
                            RetriccionEdad = 65
                        },
                        new
                        {
                            Id = 32,
                            Compania = "pelota",
                            Descripcíon = "Juguete: ¿Quién es Quién? de la compania pelota para mayores de 11 años",
                            Imagen = "",
                            Nombre = "¿Quién es Quién?",
                            Precio = 95.06m,
                            RetriccionEdad = 11
                        },
                        new
                        {
                            Id = 33,
                            Compania = "tren",
                            Descripcíon = "Juguete: avión de la compania tren para mayores de 19 años",
                            Imagen = "",
                            Nombre = "avión",
                            Precio = 427.54m,
                            RetriccionEdad = 19
                        },
                        new
                        {
                            Id = 34,
                            Compania = "tren",
                            Descripcíon = "Juguete: patito de goma de la compania tren para mayores de 64 años",
                            Imagen = "",
                            Nombre = "patito de goma",
                            Precio = 493.63m,
                            RetriccionEdad = 64
                        },
                        new
                        {
                            Id = 35,
                            Compania = "pelota",
                            Descripcíon = "Juguete: patito de goma de la compania pelota para mayores de 53 años",
                            Imagen = "",
                            Nombre = "patito de goma",
                            Precio = 669.60m,
                            RetriccionEdad = 53
                        },
                        new
                        {
                            Id = 36,
                            Compania = "muñeca",
                            Descripcíon = "Juguete: patito de goma de la compania muñeca para mayores de 3 años",
                            Imagen = "",
                            Nombre = "patito de goma",
                            Precio = 528.89m,
                            RetriccionEdad = 3
                        },
                        new
                        {
                            Id = 37,
                            Compania = "osito de peluche",
                            Descripcíon = "Juguete: Pictionary de la compania osito de peluche para mayores de 54 años",
                            Imagen = "",
                            Nombre = "Pictionary",
                            Precio = 432.07m,
                            RetriccionEdad = 54
                        },
                        new
                        {
                            Id = 38,
                            Compania = "tren",
                            Descripcíon = "Juguete: cometa de la compania tren para mayores de 38 años",
                            Imagen = "",
                            Nombre = "cometa",
                            Precio = 969.78m,
                            RetriccionEdad = 38
                        },
                        new
                        {
                            Id = 39,
                            Compania = "¿Quién es Quién?",
                            Descripcíon = "Juguete: osito de peluche de la compania ¿Quién es Quién? para mayores de 45 años",
                            Imagen = "",
                            Nombre = "osito de peluche",
                            Precio = 474.85m,
                            RetriccionEdad = 45
                        },
                        new
                        {
                            Id = 40,
                            Compania = "avión",
                            Descripcíon = "Juguete: Parchís de la compania avión para mayores de 71 años",
                            Imagen = "",
                            Nombre = "Parchís",
                            Precio = 311.82m,
                            RetriccionEdad = 71
                        },
                        new
                        {
                            Id = 41,
                            Compania = "bicicleta",
                            Descripcíon = "Juguete: muñeca de la compania bicicleta para mayores de 85 años",
                            Imagen = "",
                            Nombre = "muñeca",
                            Precio = 277.14m,
                            RetriccionEdad = 85
                        },
                        new
                        {
                            Id = 42,
                            Compania = "bicicleta",
                            Descripcíon = "Juguete: Parchís de la compania bicicleta para mayores de 48 años",
                            Imagen = "",
                            Nombre = "Parchís",
                            Precio = 844.11m,
                            RetriccionEdad = 48
                        },
                        new
                        {
                            Id = 43,
                            Compania = "avión",
                            Descripcíon = "Juguete: UNO de la compania avión para mayores de 87 años",
                            Imagen = "",
                            Nombre = "UNO",
                            Precio = 518.39m,
                            RetriccionEdad = 87
                        },
                        new
                        {
                            Id = 44,
                            Compania = "tren",
                            Descripcíon = "Juguete: Pictionary de la compania tren para mayores de 49 años",
                            Imagen = "",
                            Nombre = "Pictionary",
                            Precio = 664.44m,
                            RetriccionEdad = 49
                        },
                        new
                        {
                            Id = 45,
                            Compania = "avión",
                            Descripcíon = "Juguete: muñeca de la compania avión para mayores de 10 años",
                            Imagen = "",
                            Nombre = "muñeca",
                            Precio = 569.43m,
                            RetriccionEdad = 10
                        },
                        new
                        {
                            Id = 46,
                            Compania = "cometa",
                            Descripcíon = "Juguete: patito de goma de la compania cometa para mayores de 49 años",
                            Imagen = "",
                            Nombre = "patito de goma",
                            Precio = 180.10m,
                            RetriccionEdad = 49
                        },
                        new
                        {
                            Id = 47,
                            Compania = "tren",
                            Descripcíon = "Juguete: cometa de la compania tren para mayores de 58 años",
                            Imagen = "",
                            Nombre = "cometa",
                            Precio = 811.02m,
                            RetriccionEdad = 58
                        },
                        new
                        {
                            Id = 48,
                            Compania = "bicicleta",
                            Descripcíon = "Juguete: bicicleta de la compania bicicleta para mayores de 66 años",
                            Imagen = "",
                            Nombre = "bicicleta",
                            Precio = 363.24m,
                            RetriccionEdad = 66
                        },
                        new
                        {
                            Id = 49,
                            Compania = "¿Quién es Quién?",
                            Descripcíon = "Juguete: tren de la compania ¿Quién es Quién? para mayores de 86 años",
                            Imagen = "",
                            Nombre = "tren",
                            Precio = 427.42m,
                            RetriccionEdad = 86
                        },
                        new
                        {
                            Id = 50,
                            Compania = "muñeca",
                            Descripcíon = "Juguete: bicicleta de la compania muñeca para mayores de 14 años",
                            Imagen = "",
                            Nombre = "bicicleta",
                            Precio = 168.60m,
                            RetriccionEdad = 14
                        },
                        new
                        {
                            Id = 51,
                            Compania = "patito de goma",
                            Descripcíon = "Juguete: osito de peluche de la compania patito de goma para mayores de 20 años",
                            Imagen = "",
                            Nombre = "osito de peluche",
                            Precio = 166.22m,
                            RetriccionEdad = 20
                        },
                        new
                        {
                            Id = 52,
                            Compania = "tren",
                            Descripcíon = "Juguete: ¿Quién es Quién? de la compania tren para mayores de 65 años",
                            Imagen = "",
                            Nombre = "¿Quién es Quién?",
                            Precio = 852.57m,
                            RetriccionEdad = 65
                        },
                        new
                        {
                            Id = 53,
                            Compania = "cometa",
                            Descripcíon = "Juguete: UNO de la compania cometa para mayores de 82 años",
                            Imagen = "",
                            Nombre = "UNO",
                            Precio = 974.20m,
                            RetriccionEdad = 82
                        },
                        new
                        {
                            Id = 54,
                            Compania = "muñeca",
                            Descripcíon = "Juguete: patito de goma de la compania muñeca para mayores de 46 años",
                            Imagen = "",
                            Nombre = "patito de goma",
                            Precio = 269.37m,
                            RetriccionEdad = 46
                        },
                        new
                        {
                            Id = 55,
                            Compania = "Pictionary",
                            Descripcíon = "Juguete: Pictionary de la compania Pictionary para mayores de 82 años",
                            Imagen = "",
                            Nombre = "Pictionary",
                            Precio = 1.16m,
                            RetriccionEdad = 82
                        },
                        new
                        {
                            Id = 56,
                            Compania = "UNO",
                            Descripcíon = "Juguete: cometa de la compania UNO para mayores de 6 años",
                            Imagen = "",
                            Nombre = "cometa",
                            Precio = 285.84m,
                            RetriccionEdad = 6
                        },
                        new
                        {
                            Id = 57,
                            Compania = "avión",
                            Descripcíon = "Juguete: tren de la compania avión para mayores de 55 años",
                            Imagen = "",
                            Nombre = "tren",
                            Precio = 149.64m,
                            RetriccionEdad = 55
                        },
                        new
                        {
                            Id = 58,
                            Compania = "tren",
                            Descripcíon = "Juguete: bicicleta de la compania tren para mayores de 81 años",
                            Imagen = "",
                            Nombre = "bicicleta",
                            Precio = 227.15m,
                            RetriccionEdad = 81
                        },
                        new
                        {
                            Id = 59,
                            Compania = "¿Quién es Quién?",
                            Descripcíon = "Juguete: muñeca de la compania ¿Quién es Quién? para mayores de 89 años",
                            Imagen = "",
                            Nombre = "muñeca",
                            Precio = 653.45m,
                            RetriccionEdad = 89
                        },
                        new
                        {
                            Id = 60,
                            Compania = "cometa",
                            Descripcíon = "Juguete: avión de la compania cometa para mayores de 77 años",
                            Imagen = "",
                            Nombre = "avión",
                            Precio = 841.10m,
                            RetriccionEdad = 77
                        },
                        new
                        {
                            Id = 61,
                            Compania = "avión",
                            Descripcíon = "Juguete: tren de la compania avión para mayores de 15 años",
                            Imagen = "",
                            Nombre = "tren",
                            Precio = 146.21m,
                            RetriccionEdad = 15
                        },
                        new
                        {
                            Id = 62,
                            Compania = "tren",
                            Descripcíon = "Juguete: bicicleta de la compania tren para mayores de 73 años",
                            Imagen = "",
                            Nombre = "bicicleta",
                            Precio = 291.52m,
                            RetriccionEdad = 73
                        },
                        new
                        {
                            Id = 63,
                            Compania = "bicicleta",
                            Descripcíon = "Juguete: muñeca de la compania bicicleta para mayores de 13 años",
                            Imagen = "",
                            Nombre = "muñeca",
                            Precio = 203.41m,
                            RetriccionEdad = 13
                        },
                        new
                        {
                            Id = 64,
                            Compania = "pelota",
                            Descripcíon = "Juguete: cometa de la compania pelota para mayores de 97 años",
                            Imagen = "",
                            Nombre = "cometa",
                            Precio = 707.03m,
                            RetriccionEdad = 97
                        },
                        new
                        {
                            Id = 65,
                            Compania = "avión",
                            Descripcíon = "Juguete: UNO de la compania avión para mayores de 51 años",
                            Imagen = "",
                            Nombre = "UNO",
                            Precio = 655.99m,
                            RetriccionEdad = 51
                        },
                        new
                        {
                            Id = 66,
                            Compania = "bicicleta",
                            Descripcíon = "Juguete: pelota de la compania bicicleta para mayores de 40 años",
                            Imagen = "",
                            Nombre = "pelota",
                            Precio = 72.02m,
                            RetriccionEdad = 40
                        },
                        new
                        {
                            Id = 67,
                            Compania = "osito de peluche",
                            Descripcíon = "Juguete: tren de la compania osito de peluche para mayores de 74 años",
                            Imagen = "",
                            Nombre = "tren",
                            Precio = 629.07m,
                            RetriccionEdad = 74
                        },
                        new
                        {
                            Id = 68,
                            Compania = "avión",
                            Descripcíon = "Juguete: ¿Quién es Quién? de la compania avión para mayores de 60 años",
                            Imagen = "",
                            Nombre = "¿Quién es Quién?",
                            Precio = 373.41m,
                            RetriccionEdad = 60
                        },
                        new
                        {
                            Id = 69,
                            Compania = "bicicleta",
                            Descripcíon = "Juguete: Pictionary de la compania bicicleta para mayores de 40 años",
                            Imagen = "",
                            Nombre = "Pictionary",
                            Precio = 155.56m,
                            RetriccionEdad = 40
                        },
                        new
                        {
                            Id = 70,
                            Compania = "osito de peluche",
                            Descripcíon = "Juguete: avión de la compania osito de peluche para mayores de 24 años",
                            Imagen = "",
                            Nombre = "avión",
                            Precio = 949.72m,
                            RetriccionEdad = 24
                        },
                        new
                        {
                            Id = 71,
                            Compania = "bicicleta",
                            Descripcíon = "Juguete: UNO de la compania bicicleta para mayores de 31 años",
                            Imagen = "",
                            Nombre = "UNO",
                            Precio = 758.89m,
                            RetriccionEdad = 31
                        },
                        new
                        {
                            Id = 72,
                            Compania = "tren",
                            Descripcíon = "Juguete: ¿Quién es Quién? de la compania tren para mayores de 0 años",
                            Imagen = "",
                            Nombre = "¿Quién es Quién?",
                            Precio = 302.56m,
                            RetriccionEdad = 0
                        },
                        new
                        {
                            Id = 73,
                            Compania = "osito de peluche",
                            Descripcíon = "Juguete: ¿Quién es Quién? de la compania osito de peluche para mayores de 20 años",
                            Imagen = "",
                            Nombre = "¿Quién es Quién?",
                            Precio = 337.15m,
                            RetriccionEdad = 20
                        },
                        new
                        {
                            Id = 74,
                            Compania = "UNO",
                            Descripcíon = "Juguete: cometa de la compania UNO para mayores de 75 años",
                            Imagen = "",
                            Nombre = "cometa",
                            Precio = 642.31m,
                            RetriccionEdad = 75
                        },
                        new
                        {
                            Id = 75,
                            Compania = "osito de peluche",
                            Descripcíon = "Juguete: Parchís de la compania osito de peluche para mayores de 46 años",
                            Imagen = "",
                            Nombre = "Parchís",
                            Precio = 996.78m,
                            RetriccionEdad = 46
                        },
                        new
                        {
                            Id = 76,
                            Compania = "Parchís",
                            Descripcíon = "Juguete: muñeca de la compania Parchís para mayores de 52 años",
                            Imagen = "",
                            Nombre = "muñeca",
                            Precio = 250.58m,
                            RetriccionEdad = 52
                        },
                        new
                        {
                            Id = 77,
                            Compania = "Pictionary",
                            Descripcíon = "Juguete: pelota de la compania Pictionary para mayores de 81 años",
                            Imagen = "",
                            Nombre = "pelota",
                            Precio = 614.51m,
                            RetriccionEdad = 81
                        },
                        new
                        {
                            Id = 78,
                            Compania = "pelota",
                            Descripcíon = "Juguete: pelota de la compania pelota para mayores de 73 años",
                            Imagen = "",
                            Nombre = "pelota",
                            Precio = 807.83m,
                            RetriccionEdad = 73
                        },
                        new
                        {
                            Id = 79,
                            Compania = "bicicleta",
                            Descripcíon = "Juguete: UNO de la compania bicicleta para mayores de 19 años",
                            Imagen = "",
                            Nombre = "UNO",
                            Precio = 715.37m,
                            RetriccionEdad = 19
                        },
                        new
                        {
                            Id = 80,
                            Compania = "bicicleta",
                            Descripcíon = "Juguete: cometa de la compania bicicleta para mayores de 60 años",
                            Imagen = "",
                            Nombre = "cometa",
                            Precio = 794.59m,
                            RetriccionEdad = 60
                        },
                        new
                        {
                            Id = 81,
                            Compania = "pelota",
                            Descripcíon = "Juguete: ¿Quién es Quién? de la compania pelota para mayores de 25 años",
                            Imagen = "",
                            Nombre = "¿Quién es Quién?",
                            Precio = 461.55m,
                            RetriccionEdad = 25
                        },
                        new
                        {
                            Id = 82,
                            Compania = "muñeca",
                            Descripcíon = "Juguete: UNO de la compania muñeca para mayores de 22 años",
                            Imagen = "",
                            Nombre = "UNO",
                            Precio = 16.93m,
                            RetriccionEdad = 22
                        },
                        new
                        {
                            Id = 83,
                            Compania = "Parchís",
                            Descripcíon = "Juguete: Pictionary de la compania Parchís para mayores de 17 años",
                            Imagen = "",
                            Nombre = "Pictionary",
                            Precio = 195.71m,
                            RetriccionEdad = 17
                        },
                        new
                        {
                            Id = 84,
                            Compania = "tren",
                            Descripcíon = "Juguete: bicicleta de la compania tren para mayores de 69 años",
                            Imagen = "",
                            Nombre = "bicicleta",
                            Precio = 341.48m,
                            RetriccionEdad = 69
                        },
                        new
                        {
                            Id = 85,
                            Compania = "osito de peluche",
                            Descripcíon = "Juguete: cometa de la compania osito de peluche para mayores de 20 años",
                            Imagen = "",
                            Nombre = "cometa",
                            Precio = 84.02m,
                            RetriccionEdad = 20
                        },
                        new
                        {
                            Id = 86,
                            Compania = "Parchís",
                            Descripcíon = "Juguete: Pictionary de la compania Parchís para mayores de 0 años",
                            Imagen = "",
                            Nombre = "Pictionary",
                            Precio = 982.46m,
                            RetriccionEdad = 0
                        },
                        new
                        {
                            Id = 87,
                            Compania = "pelota",
                            Descripcíon = "Juguete: tren de la compania pelota para mayores de 28 años",
                            Imagen = "",
                            Nombre = "tren",
                            Precio = 962.85m,
                            RetriccionEdad = 28
                        },
                        new
                        {
                            Id = 88,
                            Compania = "tren",
                            Descripcíon = "Juguete: avión de la compania tren para mayores de 72 años",
                            Imagen = "",
                            Nombre = "avión",
                            Precio = 382.02m,
                            RetriccionEdad = 72
                        },
                        new
                        {
                            Id = 89,
                            Compania = "osito de peluche",
                            Descripcíon = "Juguete: bicicleta de la compania osito de peluche para mayores de 82 años",
                            Imagen = "",
                            Nombre = "bicicleta",
                            Precio = 477.02m,
                            RetriccionEdad = 82
                        },
                        new
                        {
                            Id = 90,
                            Compania = "avión",
                            Descripcíon = "Juguete: Pictionary de la compania avión para mayores de 46 años",
                            Imagen = "",
                            Nombre = "Pictionary",
                            Precio = 859.94m,
                            RetriccionEdad = 46
                        },
                        new
                        {
                            Id = 91,
                            Compania = "bicicleta",
                            Descripcíon = "Juguete: pelota de la compania bicicleta para mayores de 48 años",
                            Imagen = "",
                            Nombre = "pelota",
                            Precio = 56.13m,
                            RetriccionEdad = 48
                        },
                        new
                        {
                            Id = 92,
                            Compania = "pelota",
                            Descripcíon = "Juguete: pelota de la compania pelota para mayores de 72 años",
                            Imagen = "",
                            Nombre = "pelota",
                            Precio = 436.51m,
                            RetriccionEdad = 72
                        },
                        new
                        {
                            Id = 93,
                            Compania = "patito de goma",
                            Descripcíon = "Juguete: ¿Quién es Quién? de la compania patito de goma para mayores de 49 años",
                            Imagen = "",
                            Nombre = "¿Quién es Quién?",
                            Precio = 891.98m,
                            RetriccionEdad = 49
                        },
                        new
                        {
                            Id = 94,
                            Compania = "muñeca",
                            Descripcíon = "Juguete: Pictionary de la compania muñeca para mayores de 68 años",
                            Imagen = "",
                            Nombre = "Pictionary",
                            Precio = 742.31m,
                            RetriccionEdad = 68
                        },
                        new
                        {
                            Id = 95,
                            Compania = "UNO",
                            Descripcíon = "Juguete: Parchís de la compania UNO para mayores de 56 años",
                            Imagen = "",
                            Nombre = "Parchís",
                            Precio = 266.91m,
                            RetriccionEdad = 56
                        },
                        new
                        {
                            Id = 96,
                            Compania = "patito de goma",
                            Descripcíon = "Juguete: UNO de la compania patito de goma para mayores de 12 años",
                            Imagen = "",
                            Nombre = "UNO",
                            Precio = 625.61m,
                            RetriccionEdad = 12
                        },
                        new
                        {
                            Id = 97,
                            Compania = "UNO",
                            Descripcíon = "Juguete: cometa de la compania UNO para mayores de 35 años",
                            Imagen = "",
                            Nombre = "cometa",
                            Precio = 942.20m,
                            RetriccionEdad = 35
                        },
                        new
                        {
                            Id = 98,
                            Compania = "tren",
                            Descripcíon = "Juguete: cometa de la compania tren para mayores de 89 años",
                            Imagen = "",
                            Nombre = "cometa",
                            Precio = 480.73m,
                            RetriccionEdad = 89
                        },
                        new
                        {
                            Id = 99,
                            Compania = "UNO",
                            Descripcíon = "Juguete: patito de goma de la compania UNO para mayores de 97 años",
                            Imagen = "",
                            Nombre = "patito de goma",
                            Precio = 917.48m,
                            RetriccionEdad = 97
                        },
                        new
                        {
                            Id = 100,
                            Compania = "avión",
                            Descripcíon = "Juguete: Parchís de la compania avión para mayores de 70 años",
                            Imagen = "",
                            Nombre = "Parchís",
                            Precio = 626.30m,
                            RetriccionEdad = 70
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
